# Copyright 2026 The OpenChoreo Authors
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "events-collector.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "events-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "events-collector.selectorLabels" . | nindent 4 }}
  ports:
    {{- toYaml .Values.service.ports | nindent 4 }}
{{- end }}
